ibeta
powerResidueSymbol
hilbertsymbol
{
getPthPowerRootOfUnity
hilbertSymbol
    principalunits
    {
        localFieldFunctions
        higherUnitsResidue
        generatorsPrincipalUnits
        exponentialRepresentation
    }
}
